# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db247c0b3b7c65f9b5d8d798ae30b925"
name = "Beheer"
application_url = "https://iselectstore-marktplaats-app.vercel.app"
embedded = true

[build]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products,write_content,write_products,read_inventory"

[auth]
redirect_urls = [
  "https://iselectstore-marktplaats-app.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "https://iselectstore-marktplaats-app.vercel.app/api/webhooks/products-update"

[pos]
embedded = false
